# Write an IP problem in <'lp'> format - deer habitat model 

In [1]:
%load_ext autoreload
%autoreload 2

##LAST FINAL VERSION COLORADO - SSAFR 

from pulp import * 
import pandas as pd 
import numpy as np 
import math 
import re
import sys
import matplotlib.pyplot as plt
#print("User Current Version:-", sys.version)

#%cd "C:\Program Files\IBM\ILOG\CPLEX_Studio221\cplex\bin\x64_win64"
#!pip install cplex
import cplex
#https://perso.ensta-paris.fr/~diam/ro/online/cplex/cplex1271/refpythoncplex/html/frames.html

### 1. Import files 

In [2]:
### Added value : 
        #https://www.supplychaindataanalytics.com/augmented-epsilon-constraint-method-multi-goal-optimization-with-pulp-in-python/
        # Epsilon constraint optimization in Python
        # Published on 09/27/2021 by Keivan Tafakkori M.Sc.

### Parcels data: n°, buffer zones for each polygon, area, past harvesting and PCT, old_growth
df_sheet_2 = pd.read_excel('1-Adj_200mbuffer.xlsx', sheet_name=1)
df_sheet_2["Acre"] = df_sheet_2["Acre"].astype(int)
df_sheet_2 = df_sheet_2.fillna(0)
### growth model equations
equation_vol = pd.read_csv('Growth_volume_inc.csv', delimiter =';')
equation_merch_vol = pd.read_csv('Growth_volume_inc_mercht.csv', delimiter =';')
equation_carbon = pd.read_csv('Growth_carbon.csv', delimiter =';')


In [3]:
#Tables 
HPCT = pd.DataFrame()
HPCT = HPCT.assign(stand_i=df_sheet_2["Stand_Ipid"],  area=df_sheet_2["Acre"],H=df_sheet_2["Harvest"], 
                   PCT=df_sheet_2["PCT_YR"], SI=df_sheet_2["SSIZEC"], 
                   adj_i=df_sheet_2["Neighbor_2"], SC_SI=df_sheet_2["SC_SI"])
HPCT = HPCT.drop_duplicates(subset='stand_i', keep="first")

Buffer = pd.DataFrame()
Buffer = Buffer.assign(stand_i=df_sheet_2["Stand_Ipid"],a_buffer=df_sheet_2["Int_ac"],c_buffer=df_sheet_2["Buffer"])

### 2. Define parameters, dictionaries  

In [4]:
# 2.1. Volume and carbon increment function dictionary 
    
def set_eq (index_,eq):
    growth_eq_mercht = {}
    for i in range (len(eq)): 
    # combine SC and SI in index 
        index = index_[i]
    # extract the equation and transform it into a dictionary object 
        term = str(eq[i])
        term = re.split('[+]|(-)',term)
        term = list(filter(None, term))
        count = []
        r = 0 #element to remove 
        for j in range(len(term)):
            if "E" in term[j]:
                if term[j-1] == "-":
                    term[j] = term[j-1]+term[j]+term[j+1]+term[j+2] 
                    count.append(j-1-r)
                    r = r+1
                    count.append(j+1-r)
                    r = r+1
                    count.append(j+2-r)
                    r = r+1
                else:
                    term[j] = term[j]+term[j+1]+term[j+2]
                    count.append(j+1-r)
                    r = r+1
                    count.append(j+2-r)
                    r = r+1
        for k in count: 
            term.remove(term[k])
        count = []
        r = 0
        for j in range(len(term)):
            if "-" == term[j]:
                term[j] = term[j]+term[j+1]
                count.append(j+1-r)
                r = r + 1
        for k in count: 
            term.remove(term[k])
        eq_elt = {}
        for j in range(len(term)):
            info = term[j].split('x')
            info = [i.replace(",", ".") for i in info]
            if "E" in info: 
                exp_number = info[0]
                float_number = float(exp_number)
                info[0] = float_number
            if ' ' in info: 
                info = [str(i).replace(" ", "") for i in info]
                info[0] = float(info[0])
                eq_elt.update({1 :info[0], 0:0})
            elif len(info) == 1:
                for l in range(len(info)):
                    if info[l] == '': 
                        info[l] = 0
                info = [str(i).replace(" ", "") for i in info]
                info = [float(i) for i in info]
                eq_elt.update({0 :info[0]})
            else:
                for l in range(len(info)):
                    if info[l] == '': 
                        info[l] = 0
                info = [str(i).replace(" ", "") for i in info]
                info = [float(i) for i in info]
                eq_elt.update({info[1]:info[0]})
    #dictionary with SC_SI and it equation encoded as an embeded dictionary 
        growth_eq_mercht.update({index: eq_elt})
    return growth_eq_mercht

### MERCHANTABLE VOLUME DIC. [MBF]
SC = equation_merch_vol["SC"]
SI = equation_merch_vol["SI"]
eq = equation_merch_vol["Unnamed: 2"]
index_ = []
for i in range(len(eq)): 
    var = "SC_"+str(SC[i])+"_SI_"+str(SI[i])
    index_.append(var)
growth_eq_mercht = set_eq(index_,eq)

### GROSS TIMBER VOLUME DIC. [cu. feet]
SC = equation_vol["SC"]
SI = equation_vol["SI"]
eq = equation_vol["eq"]

index_ = []
for i in range(len(eq)): 
    var = "SC_"+str(SC[i])+"_SI_"+str(SI[i])
    index_.append(var)  
growth_eq_vol = set_eq(index_,eq)

### CARBON ACCRETION DIC. [MgC/ac = tC/ac]
Man = equation_carbon["Man"]
eq = equation_carbon["eq"]
growth_eq_carbon = set_eq(Man,eq) #Mg/ac

# Set a function that would read the equations stored in your dictionary 
def eval_poly_dict(poly, x, y):
    return sum([poly[y][power]*x**power for power in poly[y]])

# test 
X = 80
a =eval_poly_dict(growth_eq_vol, X, 'SC_VI_SI_60')  
## !!!! growth_eq_vol cubic feet vs growth_eq_mercht in MBF 
print(a)


# 2.2. Carbon decay functions 
# What remains after harvest is belowground biomass (20% of total biomass) and residues (40% of 80%) 
amount_left=(20/100)+(40/100)*(80/100)
# When a parcel is harvested 60% si removed from land, 13% of the 60% is converted to long-term product
amount_lgproduct=(13/100)*(60/100)*(80/100)
   ### if thinned, everything is left on the floor and thus refer to growth_carbon[T20] or [T30]
def coarse_debris_decay(Bo,t):
    debris_biomass = Bo*amount_left*(0.3870*math.exp(-0.1429*t))+(0.6198*math.exp(-0.00223*t))
    return debris_biomass
def harvest_accretion(Bo,t):
    harvest_biomass = Bo*103.16*math.exp(-0.031*t)/100*amount_lgproduct
    return harvest_biomass

# Source:
#https://cbmjournal.biomedcentral.com/articles/10.1186/s13021-015-0035-4#Sec3


4387.32


In [5]:
# 2.3. Data parameters  
mid_point = 2.5 # an action is estimated to happen at the mid-point of 5-year periods 
n_periods = 14 # number of periods in the planning horizon (70 years/5)

i_yr = 2015 # starting year 

n_stands = len(HPCT) #number of polygons 
M = n_stands + 1  # big number 

## PCT parameters 
min_yr = 15 # minimal age before PCT
max_yr = 40 # maximal age for PCT treatements 

## Cover parameters 
min_yr_cover = 120 # minimal age for stand to be considered as cover 

## Harvest parameters 
min_hyr = 55 # minimal age before harvesting 
    ### set the number of periods to prevent harvesting after PCT 
n_harv_pct = 2

min_vol = 20.5 #MBF/ac min merchantable volume 
max_start_vol=98+1
max_volume=241+1

# Source 
# https://tind-customer-agecon.s3.amazonaws.com/0d218c56-21cd-4a6f-9ded-711620b176dd?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27tb1273.pdf&response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=86400&X-Amz-Credential=AKIAXL7W7Q3XHXDVDQYS%2F20220519%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20220519T211917Z&X-Amz-Signature=2f733b3d86f854ddb3b1fbab86865135966db323573c7649a480441933c66d95
### volume data for unmanaged hemlock 


In [6]:
# 2. 4. Set a dictionary that enumerates for each polygon k, the polygons m
   #that are within a buffer zone of 200m 
Buffer_dic = {}
cell_buffer = {}
cell = []
cell_buff =[]
count = 0 
for m in range(len(Buffer["stand_i"])):
    first = Buffer["stand_i"][m]
    if first not in cell: 
        cell.append(first)
        for i in range(len(Buffer["stand_i"])):
            second = Buffer["stand_i"][i]
            if first == second: 
                cells = Buffer["c_buffer"][i] 
                if cells != first:
                    area = Buffer["a_buffer"][i]
                    cell_buffer.update({cells:area})
        Buffer_dic.update({first:cell_buffer})
        cell_buffer = {}

In [7]:
# 2. 5. Stand/Management Unit characteristics 
## Stand number 
N_stands = np.array(HPCT["stand_i"])
N_stands = np.ndarray.tolist(N_stands)

# STAND ID DIC. 
stands_dic = {}
number = 0
for m in range(len(N_stands)):
    number = number+1 
    stand = N_stands[m]
    stands_dic.update({number:stand})

# STAND AREA DIC.
A_stands = np.array(HPCT["area"])
area_dic = {}
for m in range(len(N_stands)):
    stand = N_stands[m]
    area = A_stands[m]
    area_dic.update({stand:area})

# PREVIOUS ACTIVITIES (Harvesting and PCT)
Yr_harvest = np.array(HPCT["H"])
Yr_PCT = np.array(HPCT["PCT"])
Yr_OG = np.array(HPCT["SI"])

### List previous harvest - RECORD Y m,-t :         
new_Y_m = []
new_Y_p = []
new_Y = {}
for i in range (len(Yr_harvest)): 
    if Yr_harvest[i] != 0: 
        new_Y_m.append(N_stands[i])
        a = math.floor((Yr_harvest[i]-i_yr-1)/5)
        new_Y_p.append(math.floor((Yr_harvest[i]-i_yr-1)/5))
    elif Yr_OG[i] == 4:
        new_Y_m.append(N_stands[i])
        a = -((min_yr_cover/5) +3)
        new_Y_p.append(-((min_yr_cover/5) +3)) 
        #considered min age for old growth (period of 5 years so 5*26)
    else: 
        new_Y_m.append(N_stands[i])
        a = -((min_yr_cover/5) +1)
        new_Y_p.append(-((min_yr_cover/5) +1))
    new_Y.update({N_stands[i]:a})

### List previous PCT - RECORD X m,-t : 
add_var = []
new_X_m = []
new_X_p = []
new_X = {}
for i in range (len(Yr_PCT)): 
    if Yr_PCT[i] != 0: 
        new_X_m.append(N_stands[i])
        a = math.floor((Yr_PCT[i]-i_yr-1)/5)
        new_X_p.append(math.floor((Yr_PCT[i]-i_yr-1)/5))
        new_X.update({N_stands[i]:a})        

### STAND TIMBER VOLUME DIC.
#Define a dictionary setting the timber volume of each polygon for each period 
    # ~ site class and site index 
SC_SI = pd.DataFrame()
SC_SI = SC_SI.assign(stand_i=np.array(HPCT["stand_i"]), SC_SI=np.array(HPCT["SC_SI"]))
volume = {} # timber_volume dictionary 
start_vol = {} # timber_volume for parcels starting from age 0  
for k in range(len(N_stands)):
    a = []
    a_mercht =[]
    start = []
    start_mercht = []
    a.append(0)
    a_mercht.append(0)
    for i in range(n_periods+1):
        Age_mt = (i-new_Y_p[k])*5
        
        SC_SIm = SC_SI["SC_SI"][k]
        if SC_SIm == 0:
            SC_SIm =  SC_SI["SC_SI"][1]
        b = eval_poly_dict(growth_eq_vol, Age_mt, SC_SIm)
        b_mercht = eval_poly_dict(growth_eq_mercht, Age_mt, SC_SIm)
        b=round(b)
        b_mercht=round(b_mercht)
        c = eval_poly_dict(growth_eq_vol, (i)*5, SC_SIm)
        c = round(c)
        c_mercht = eval_poly_dict(growth_eq_mercht, (i)*5, SC_SIm)
        c_mercht = round(c_mercht)
        if b < 0: 
            b = 0 
        if c < 0: 
            c = 0
        if b_mercht < 0: 
            b_mercht = 0 
        if c_mercht < 0: 
            c_mercht = 0
        a.append(b) #MBF/ac
        a_mercht.append(b_mercht)
        start.append(c)
        start_mercht.append(c_mercht)
    volume.update({N_stands[k]:a_mercht}) 
    start_vol.update({N_stands[k]:start_mercht})

#PCT DIC. when PCT is conducted, 90% of the basal area is removed, thus the growth of a stand is slowdowned
pct_dic = {-1:0, -2:0, -3:0,-4:0, -5:0, -6:0, -7:0, -8:0, -9:0, -10:0, -11:0, -12:0,-13:0,-14:0,0:0,
           8:4,7:4,6:4,5:3,4:3,3:3, # 8:5,7:5,6:4,5:3,4:3,3:2,
           1:0,2:0,9:0,10:0,11:0,12:0,13:0,14:0,15:0,16:0,17:0,18:0
           ,19:0,20:0,21:0,22:0,23:0,24:0,25:0,26:0,27:0,28:0,29:0,30:0,31:0,32:0,33:0,34:0,35:0,36:0,37:0,38:0,39:0, 40:0,41:0, 42:0} # 10% of the stand is retained 
# Source 
# https://tind-customer-agecon.s3.amazonaws.com/0d218c56-21cd-4a6f-9ded-711620b176dd?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27tb1273.pdf&response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=86400&X-Amz-Credential=AKIAXL7W7Q3XHXDVDQYS%2F20220519%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Date=20220519T211917Z&X-Amz-Signature=2f733b3d86f854ddb3b1fbab86865135966db323573c7649a480441933c66d95
### volume data for unmanaged hemlock 


In [8]:
# 2.5 Coefficients
        ### HARVEST coefficient : timber volume if the parcel is to be harvested at period p

count_dic = {}
coeffH_dic = {}
for m in range(n_stands):
    age_i = -new_Y_p[m]
    stand = new_Y_m[m]
    SC_SIm = SC_SI["SC_SI"][m]
    if SC_SIm ==0:
        SC_SIm = SC_SI["SC_SI"][1]
        ### Case 1: No action conducted 
    var = str(stand)+"_"+str(0)+"_"+str(0)
    vol =eval_poly_dict(growth_eq_mercht, (age_i+n_periods)*5, SC_SIm)
    vol=round(vol)
    count_dic.update({var:vol})
        # Case 2: Only PCTed  
    for pct in range(1,n_periods+1):
        if pct+age_i >=min_yr/5 and pct+age_i <= max_yr/5:
            var = str(stand)+"_"+str(0)+"_"+str(pct)
            vol =eval_poly_dict(growth_eq_mercht, (age_i+n_periods-pct_dic[age_i+pct])*5, SC_SIm)
            vol=round(vol)
            count_dic.update({var:vol})
        # Case 3: Only harvested
    for harvest in range(1,n_periods+1):
        var = str(stand)+"_"+str(harvest)+"_"+str(0)
        vol =eval_poly_dict(growth_eq_mercht, (age_i+harvest)*5, SC_SIm)
        vol=round(vol)
        if age_i+harvest >=min_hyr/5 and vol >=min_vol:
            count_dic.update({var:vol})
            # Case 4: PCT after havest  
            for pct in range(harvest,n_periods+1):
                if pct-harvest >=min_yr/5 and pct-harvest <= max_yr/5:
                    var = str(stand)+"_"+str(harvest)+"_"+str(pct)
                    vol = eval_poly_dict(growth_eq_mercht, (age_i+harvest)*5, SC_SIm)
                    vol=round(vol)
                    count_dic.update({var:vol})
        # Case 5: PCTed before harvest 
        for pct in range(1,harvest):
            if pct+age_i >=min_yr/5 and pct+age_i <= max_yr/5 and pct+n_harv_pct < harvest:
                var = str(stand)+"_"+str(harvest)+"_"+str(pct)
                vol = eval_poly_dict(growth_eq_mercht, (age_i+harvest-pct_dic[age_i+pct])*5, SC_SIm)
                vol=round(vol)
                if vol >= min_vol:
                    count_dic.update({var:vol})
    # Other cases : if PCT and/or harvest cannot be done 
    key_list = list(count_dic.keys())
    for i in range(n_periods+1):
        for j in range(n_periods+1):
            var = str(stand)+"_"+str(i)+"_"+str(j)
            if var not in key_list:
                count_dic.update({var:0})           
    coeffH_dic.update({stand:count_dic})
    count_dic = {}



In [9]:
### BIOMASS relative gross volume*wood density 
#: total biomass at the end of the planning horizon given PCT and/or harvest or no action 
trend=0 #if want to extend the accounted time for carbon sequestration (in 70 years, 100 years etc.)
coeffC_dic2 = {}
for m in range(n_stands):
    age_i = -new_Y_p[m]
    stand = new_Y_m[m]
    SC_SIm = SC_SI["SC_SI"][m]
    if SC_SIm ==0:
        SC_SIm = SC_SI["SC_SI"][1]
    # Case 1: unmannaged stand
    var = str(stand)+"_"+str(0)+"_"+str(0)
    biomass = eval_poly_dict(growth_eq_carbon,(age_i+n_periods+trend)*5,"UM")
    count_dic.update({var:round(biomass)})
    for pct in range(1,n_periods+1):
        if pct+age_i >=min_yr/5 and pct+age_i <= max_yr/5:
            # Case 2: only PCTed stand 
            if pct <= 25/5: 
                var = str(stand)+"_"+str(0)+"_"+str(pct)
                biomass=eval_poly_dict(growth_eq_carbon,(age_i+n_periods+trend)*5,"T20")
            elif pct > 25/5: 
                var = str(stand)+"_"+str(0)+"_"+str(pct)
                biomass=eval_poly_dict(growth_eq_carbon,(age_i+n_periods+1+trend)*5,"T30")#soften the trend
            count_dic.update({var:round(biomass)})
            # Case 3: PCTed first, then harvested 
            for harvest in range(pct,n_periods+1):
                if harvest > n_harv_pct+pct:
                    vol_exported = eval_poly_dict(growth_eq_mercht,(age_i+harvest-pct_dic[age_i+pct])*5, SC_SIm)
                    vol_exported = round(vol_exported)
                    if age_i+harvest >=min_hyr/5 and vol_exported >=min_vol:
                        if pct+age_i <= 25/5: 
                            var = str(stand)+"_"+str(harvest)+"_"+str(pct)
                            print(var, "25")
                            biomass=eval_poly_dict(growth_eq_carbon,(age_i+harvest)*5,"T20")
                            print(biomass, "25")
                        elif pct+age_i > 25/5 : 
                            var = str(stand)+"_"+str(harvest)+"_"+str(pct)
                            biomass=eval_poly_dict(growth_eq_carbon,(age_i+harvest+1)*5,"T30")
                        add1 = coarse_debris_decay(biomass,(n_periods+trend-harvest)*5)
                        add2 = harvest_accretion(biomass,(n_periods+trend-harvest)*5)
                        biomass_afterharv=eval_poly_dict(growth_eq_carbon,(n_periods+trend-harvest)*5,"UM")
                        biomass=add1+add2+biomass_afterharv
                        count_dic.update({var:round(biomass)})
        # Case 4 : Only harvested 
        for harvest in range(1,n_periods+1):
            vol_exported = eval_poly_dict(growth_eq_mercht, (age_i+harvest)*5, SC_SIm)
            vol_exported = round(vol_exported)
            if age_i+harvest >=min_hyr/5 and vol_exported >=min_vol:
                var = str(stand)+"_"+str(harvest)+"_"+str(0)
                biomass=eval_poly_dict(growth_eq_carbon,(age_i+harvest)*5,"UM")
                add1 = coarse_debris_decay(biomass,(n_periods+trend-harvest)*5)
                add2 = harvest_accretion(biomass,(n_periods+trend-harvest)*5)
                biomass_afterharv=eval_poly_dict(growth_eq_carbon,(n_periods+trend-harvest)*5,"UM")
                biomass=add1+add2+biomass_afterharv
                count_dic.update({var:round(biomass)})
                # Case 5: Harvested, then PCTed 
                for pct in range(harvest,n_periods+1):
                    if pct> 2+harvest and pct-harvest <= max_yr/5:
                        biomass=eval_poly_dict(growth_eq_carbon,(age_i+harvest)*5,"UM")
                        if pct <= 25/5: 
                            var = str(stand)+"_"+str(harvest)+"_"+str(pct)
                            biomass_afterharv=eval_poly_dict(growth_eq_carbon,(n_periods+trend-harvest)*5,"T20")
                            add1 = coarse_debris_decay(biomass,(n_periods+trend-harvest)*5)
                            add2 = harvest_accretion(biomass,(n_periods+trend-harvest)*5)
                            biomass=add1+add2+biomass_afterharv
                            count_dic.update({var:round(biomass)})
                        elif pct > 25/5: 
                            var = str(stand)+"_"+str(harvest)+"_"+str(pct)
                            biomass_afterharv=eval_poly_dict(growth_eq_carbon,(n_periods+trend-harvest+1)*5,"T30")
                            add1 = coarse_debris_decay(biomass,(n_periods+trend-harvest)*5)
                            add2 = harvest_accretion(biomass,(n_periods+trend-harvest)*5)
                            biomass=add1+add2+biomass_afterharv
                            count_dic.update({var:round(biomass)})
    key_list = list(count_dic.keys())
    for i in range(n_periods+1):
        for j in range(n_periods+1):
            var = str(stand)+"_"+str(i)+"_"+str(j)
            if var not in key_list:
                count_dic.update({var:0})
    coeffC_dic2.update({stand:count_dic})
    count_dic = {} 




### 3. Decision Variables 

In [10]:
 
## X m, t - stand m to be PCTed in time period t  _ Xm,t=1; 0 otherwise 
X_variable_names = [str(i) + ',' + str(j) for i in N_stands for j in range (n_periods+1)]
DV_X_variables = LpVariable.matrix("X", X_variable_names, cat = "Binary", lowBound= 0 )
X_allocation = np.array(DV_X_variables).reshape(n_stands,14+1)

## Y m, t - stand m to be harvested in time period t _ Ym,t=1; 0 otherwise 
Y_variable_names = [str(i) + ',' + str(j) for i in N_stands for j in range (n_periods+1)]
DV_Y_variables = LpVariable.matrix("Y", Y_variable_names, cat = "Binary", lowBound= 0 )
Y_allocation = np.array(DV_Y_variables).reshape(n_stands,14+1)

### Y m,h,p
Yhp_variable_names = [str(i) + ',' + str(j) + ',' + str(k) 
                        for i in N_stands for j in range (n_periods+1)
                       for k in range (n_periods+1)]
IV_Yhp_variables = LpVariable.matrix("Yhp", Yhp_variable_names, cat = "Binary", lowBound= 0 )
Yhp_allocation = np.array(IV_Yhp_variables).reshape(n_stands,14+1,14+1)

### C m,h,p 
Chp_variable_names = [str(i) + ',' + str(j) + ',' + str(k) 
                        for i in N_stands for j in range (n_periods+1)
                       for k in range (n_periods+1)]
IV_Chp_variables = LpVariable.matrix("Chp", Chp_variable_names, cat = "Binary", lowBound= 0 )
Chp_allocation = np.array(IV_Chp_variables).reshape(n_stands,14+1,14+1)

### 4. State Variables

In [11]:
## past activities variables
# PCT 
record_X_variables = [str(j) + ',' + str(new_X_p[new_X_m.index(j)]) for j in new_X_m]
DV_Xr_variables = LpVariable.matrix("X", record_X_variables, cat = "Binary", lowBound= 0 )
Xr_allocation = np.array(DV_Xr_variables).reshape(len(new_X_p))
# Harvesting       
record_Y_variables = [str(j) + ',' + str(new_Y_p[new_Y_m.index(j)]) for j in new_Y_m]
DV_Yr_variables = LpVariable.matrix("Y", record_Y_variables, cat = "Binary", lowBound= 0 )
Yr_allocation = np.array(DV_Yr_variables).reshape(len(new_Y_p))

### Indicator Variables 

In [12]:
# Forage 
## delta m,t - is 1 if stand m is to be considered as forage stand in time t; 0 otherwise 
delta_variable_names = [str(i) + ',' + str(j) for i in N_stands for j in range (n_periods+1)]
IV_delta_variables = LpVariable.matrix("delta", delta_variable_names, cat = "Binary", lowBound= 0 )
delta_allocation = np.array(IV_delta_variables).reshape(n_stands,14+1)

# Cover 
## omega m,t - cover habitat
omega_variable_names = [str(i) + ',' + str(j) for i in N_stands for j in range (n_periods+1)]
IV_omega_variables = LpVariable.matrix("omega", omega_variable_names, cat = "Binary", lowBound= 0 )
omega_allocation = np.array(IV_omega_variables).reshape(n_stands,14+1) 

# Accessible Forage 
## alpha m,t - usable habitat by deer 
alpha_variable_names = [str(i) + ',' + str(j) for i in N_stands for j in range (n_periods+1)]
IV_alpha_variables = LpVariable.matrix("alpha", alpha_variable_names, cat = "Binary", lowBound= 0 )
alpha_allocation = np.array(IV_alpha_variables).reshape(n_stands,14+1)

# Min accessible forage per period 
alpha_min_variable_names = [str(i) for i in range (n_periods+1)]
IV_alpha_min_variables = LpVariable.matrix("alpha_min", alpha_min_variable_names, cat = "Integer", lowBound= 0 )
alpha_min_allocation = np.array(IV_alpha_min_variables).reshape(14+1)

## 7 ## Evaluation functions _ Variables 

# Age of stands 
age_variable_names = [str(i) + ',' + str(j) for i in N_stands for j in range (n_periods+1)]
IV_age_variables = LpVariable.matrix("age", age_variable_names, cat = "Integer", lowBound= 0 )
age_allocation = np.array(IV_age_variables).reshape(n_stands,14+1)

# Area of accessible forage habitat 
area_variable_names = [str(i) for i in range (n_periods+1)]
area_variables = LpVariable.matrix("Area", area_variable_names, cat = "Continuous", lowBound= 0 )
area_allocation = np.array(area_variables).reshape(n_periods+1)

# number of harvest activities 
NH_variable_names = [str(i) for i in range (n_periods+1)]
NH_variables = LpVariable.matrix("NH", NH_variable_names, cat = "Continuous", lowBound= 0 )
NH_allocation = np.array(NH_variables).reshape(n_periods+1)

# number of forage habitat 
ND_variable_names = [str(i) for i in range (n_periods+1)]
ND_variables = LpVariable.matrix("ND", ND_variable_names, cat = "Continuous", lowBound= 0 )
ND_allocation = np.array(ND_variables).reshape(n_periods+1)

# number of accessible forage habitat 
NAF_variable_names = [str(i) for i in range (n_periods+1)]
NAF_variables = LpVariable.matrix("NAF", NAF_variable_names, cat = "Continuous", lowBound= 0 )
NAF_allocation = np.array(NAF_variables).reshape(n_periods+1)

# number of PCT
NPCT_variable_names = [str(i) for i in range (n_periods+1)]
NPCT_variables = LpVariable.matrix("NPCT", NPCT_variable_names, cat = "Continuous", lowBound= 0 )
NPCT_allocation = np.array(NPCT_variables).reshape(n_periods+1)

# Harvested timber volume
Vharv_variable_names = [str(i) for i in range (n_periods+1)]
Vharv_variables = LpVariable.matrix("Vharv", Vharv_variable_names, cat = "Continuous", lowBound= 0 )
Vharv_allocation = np.array(Vharv_variables).reshape(n_periods+1)

# Total area 
AREA = LpVariable("AREA", cat="Continuous", lowBound=0)
# Number of Yhp ==1 (check if = number of parcels)
NYhp = LpVariable("NYhp", cat="Continuous", lowBound=0)

In [13]:
new_Y_p = [int(i) for i in new_Y_p]

### 7. Constraints 

In [14]:
# 7. Constraints 

# CONSTRAINTS DIC. 
cons = {}

# CONSTRAINT LIST:
    ## Constrain 1: Forage habitat 
### delta m,p+1 = Xm,p + Ym,p + Xm,p-1 + Ym,p-1
###  if p = 0 
    ### delta m,p+1 = Xm,p + Ym,p
### if the polygon has already been harvested or PCT max 10 years before starting the optimization 
    ### delta m, 0 = 1 
### the max time a polygon can be considered as forage habitat is 6 periods 

    ## Constraint 2: One PCT and one harvest 
### SUM Xm,p <= 1 
### SUM Ym,p <= 1 with p >= 0 

    ## Constraint 3 : Case scenario 
### Harvest can only be done if the timber coefficient previously calculated is != 0 
### for Yhp m, h, 0: we need to assess if Ym,h equals 1 and if the sum of Xm,p equals = 0
# this constraints account for parcels that are just harvested and not pcted 
### otherwise, Yhp m, h, p turns on if Ym,h and Xm,p == 1 
### Yhp m, h, p ==1 if parcel m is to be harvested at period h and pcted at period p 

    ## Age function 
### Age m,p = p - past_harv_period + Sum(Ym,p'*(past_harv_period-p')) for p' in range (0,p)

    ## Constraint 4: PCT conditions 
### (40-Age m,p) + (1-Xm,p)*m >= 0 
 
    ## Constraints 5: Old growth - cover type 
# Age m,p - 24*omega m,p >= 0 
######  ==> forces omega to turn 0 if too young 
### m*omega m,p + 24 >= (1- Sum Ym,p) + Age m,p 
##### ==> if age is equal to or greater than 120 years omega would be forced to turn on 

    ## Constraint 6: Habitat availability
# alpha[m][p] <= Sum omega[n][p]
# alpha[m][p] <= delta[m][p]
# Sm set of parcels n that are close enough to polygon m (200m)

    #Constraint 7: maximize min accessible forage habitat 
#Sum(alpha[m][p] for m in range(n_stands)) >= alpha_min_allocation[p]

    # Constraint 8: bounds on variables to ensure even_flow 
    
# No old-growth harvest constraint: optional  
"""for m in range(n_stands):
    if new_Y_p[m] < -26:
        cons.update({"OG_"+str(m):(lpSum(Y_allocation[m][p] for p in range (1,n_periods+1))<=0)})

 #   model+=(lpSum(delta_allocation[m][p] for p in range(1,n_periods+1)) <= 6, "tot_delta_m"+str(m))"""

## Volume function (dynamic one, not included in this code)
   # t_volume[m][p] == unmanaged_stand_volume[m][p] + (reset_vol[m][k]-unmanaged_stand_volume[m][p])*Y[m][p] 
         ### if harvested the counter reset to 0 at p_harvest+1
    #                  + (unmanaged_stand_volume[m][p-1]-unmanaged_stand_volume[m][p])*X[m][k]
        ### if PCTed the volume for the next period will be the one at p-1 
    #                  + (unmanaged_stand_volume[m][p]-unmanaged_stand_volume[m][p-1])*zeta[m][k]
        ### if PCT and harvest are to be conducted, PCT treatment would not be considered 
    #                  + reset_vol[m][p-k-1]*first[m][k], for k in range 0,p
        ### if harvest happens before PCT 
         # Zeta =  
         # Y m,p + SUM X m,p 
         ### switches on if Y and Sum X is on 
        # First = Zeta 
        ###  switches on if Y happens before X 


'for m in range(n_stands):\n    if new_Y_p[m] < -26:\n        cons.update({"OG_"+str(m):(lpSum(Y_allocation[m][p] for p in range (1,n_periods+1))<=0)})\n\n #   model+=(lpSum(delta_allocation[m][p] for p in range(1,n_periods+1)) <= 6, "tot_delta_m"+str(m))'

#### 7.1. Constraint 1: forage habitat 

In [15]:
for m in range (n_stands):
    for p in range (n_periods+1):
        if p <= n_periods-1 and p>0:  
            cons.update({"FH_1_"+str(m+1) + "_" + str(p+1):(delta_allocation[m][p+1] == X_allocation[m][p] + Y_allocation[m][p] + #changed here
                      X_allocation[m][p-1] + Y_allocation[m][p-1])})
        elif p == 0: 
            if new_Y[new_Y_m[m]]== -1: 
                # does not account for recent PCT
                index = N_stands.index(new_Y_m[m])
                cons.update({"FH_1_" + str(m+1) + "_" + str(p+1):(delta_allocation[index][1] == 1
                                                                      )})
            elif new_Y[new_Y_m[m]]== 0: 
                index = N_stands.index(new_Y_m[m])
                cons.update({"FH_1_" + str(m+1) + "_" + str(p+1):(delta_allocation[index][1] == 1
                      )})
                cons.update({"Y0_"+str(m):Y_allocation[m][0]==1})
            else: 
                cons.update({"F1_"+str(m):delta_allocation[m][1]==0})
                cons.update({"Y0_"+str(m):Y_allocation[m][0]==0})
                cons.update({"X0_"+str(m):X_allocation[m][0]==0}) 


#### 7.2. Constraint 2: One PCT and One Harvest during the planning horizon

In [16]:
## Constraint 2: One PCT and one harvest 
### SUM Xm,p <= 1 
### SUM Ym,p <= 1 with p >= 0 
for m in range(n_stands): 
    lpSum(X_allocation[m][p] for p in range(1,n_periods+1))<=1, "One_PCT_" + str(m+1)
    cons.update({"One_harv_" + str(m+1):lpSum(Y_allocation[m][p] for p in range(1,n_periods+1))<=1}) 

# if the carbon coefficient previously calculated (CoeffC_dic2[m_h_p]) == 0, then Yhp[m_h_p] == 0 
Yhpvar_dic={}
for m in range(n_stands):
    for h in range(n_periods+1):
        for p in range(n_periods+1):
            var=str(N_stands[m])+"_"+str(h)+"_"+str(p)
            if coeffC_dic2[N_stands[m]][var]==0.0:
                cons.update({"no_harvest"+str(h)+"_"+str(p):Yhp_allocation[m][h][p] == 0})
            else:
                Yhpvar_dic.update({str(N_stands[m])+"_"+str(h)+"_"+str(p):[h,p]})


#### 7.3. Constraint 3: No action constraints

In [17]:
## Constraint 3:to track which treatments allocated to unit management m  
for m in range(n_stands):
    for p in range(1,n_periods+1):
        # constraints PCT allocation 
        cons.update({"Vol_PCT"+str(m)+"_"+str(p):
                     (lpSum(Yhp_allocation[m][h][p]
                            #*coeffH_dic[N_stands[m]][str(N_stands[m])+"_"+str(h)+"_"+str(p)]
                       for h in range(n_periods+1))
                       >= X_allocation[m][p])})
    #only allow one possibility of action (none, PCT+harvest, just PCT or just harvest)
    cons.update({"Vhp"+str(m):(lpSum(Yhp_allocation[m][h][p] 
                                                for h in range(n_periods+1)
                                                for p in range(n_periods+1)) == 1)})
    for h in range(n_periods+1):
        #constraints harvest actions 
        cons.update({"Vol_Harv"+str(m)+"_"+str(h):
                     (lpSum(Yhp_allocation[m][h][p]
                            *coeffH_dic[N_stands[m]][str(N_stands[m])+"_"+str(h)+"_"+str(p)] 
                      for p in range(n_periods+1)) >= (min_vol)*Y_allocation[m][h])})
        for p in range(0,n_periods+1):
            if p==0 and h!=0:
                # Vhp m, h,0 variables account for management unit that are only harvested
                cons.update({"Vhp_0_"+str(m)+"_"+str(h)+"_"+str(p):
                             2*Yhp_allocation[m][h][p] <= Y_allocation[m][h]+(1-lpSum(X_allocation[m][p]
                                                                                      for p in range(n_periods+1)))})
                cons.update({"Vhp_00_"+str(m)+"_"+str(h)+"_"+str(p):
                             (Y_allocation[m][h] + (1-lpSum(X_allocation[m][p]
                                                           for p in range(n_periods+1)))-Yhp_allocation[m][h][p]<=1)})
            elif h!=0 and p!=0: 
                cons.update({"Vhp_2_"+str(m)+"_"+str(h)+"_"+str(p):
                             (2*Yhp_allocation[m][h][p] <= Y_allocation[m][h] + X_allocation[m][p])})
                cons.update({"Vhp_3_"+str(m)+"_"+str(h)+"_"+str(p):
                             (Y_allocation[m][h] + X_allocation[m][p]-Yhp_allocation[m][h][p]<=1)})

#### 7.4. Age function 

In [18]:
# Function Age : accounts for harvest treatments
for m in range(len(N_stands)): 
    for t in range(1,n_periods+1): 
        cons.update({"age_" + str(m) + "_"+ str(t):(age_allocation[m][t] == 
               t - new_Y_p[m] + lpSum(Y_allocation[m][p]*(new_Y_p[m]-p) for p in range(1, t)) # to account for 
                        )})

#### 7.5. Constraint 4: PCT conditions 

In [19]:
# make sure that stand is bellow 40 to be allowed to be PCTed 
### (40/5-Age m,p) + (1-Xm,p)*M >= 0 
for m in range(n_stands): 
    for t in range(1,n_periods + 1):
        cons.update({"PCT40_"+ str(m+1)+ "_"+ str(t):(0 <= (1-X_allocation[m][t])*40 + max_yr/5 - #M    
                          (t - new_Y[new_Y_m[m]] + 
                           lpSum(Y_allocation[m][p]*(new_Y[new_Y_m[m]]-p) for p in range(1, t))) 
                     )})

#### 7.6 Constraint 5: Old Growth - cover type 

In [20]:
## Constraints 6: Old growth - cover type 
## a) turn all young stage to 0 
# Age m,p - 24*omega m,p >= 0 

for m in range(n_stands): 
    for t in range(1,n_periods + 1):
        cons.update({"Cover24_"+ str(m) + "_" +str(t):(t - new_Y[new_Y_m[m]] + lpSum(Y_allocation[m][p]*(new_Y[new_Y_m[m]]-p) 
                                                for p in range(1, t)) 
                    - (omega_allocation[m][t]*min_yr_cover/5) >= 0
                     )})
                      

In [21]:
## Constraint 6: Old growth - cover type 
### b) ensure that all stands over 24 will turn 1 
### m*omega m,p + 24 >= (1- Sum Ym,p) + Age m,p 
for m in range(n_stands):
    for t in range(1,n_periods + 1):
        cons.update({"Cover_on_"+str(m)+ "_" +str(t):(30*omega_allocation[m][t] + min_yr_cover/5 #40
                         >= 1-lpSum(Y_allocation[m][p] for p in range(1, t)) + t - new_Y[new_Y_m[m]]
                         + lpSum(Y_allocation[m][p]*(new_Y[new_Y_m[m]]-p) for p in range(1, t)) 
                         )})

#### 2.7. Constraint 6: Defining accessible forage habitat for deer 


In [22]:
for i in Buffer_dic: 
    key_list = list(Buffer_dic[i].keys())
    if key_list != []:
        for p in range(1,n_periods + 1): ###
            index = N_stands.index(i)
            index_close = []
            for keys in key_list:
                index_close.append(N_stands.index(keys))
            cons.update({"if_delta_alpha_"+ str(i) + "_" + str(p):
                         (alpha_allocation[index][p]<=delta_allocation[index][p] 
                    )})
            cons.update({"if_omega_alpha_"+ str(i) + "_" + str(p):
                         (alpha_allocation[index][p]<=lpSum(omega_allocation[n][p] for n in index_close) 
                    )})
            ### previously used constraint 
            #model+=(alpha_allocation[index][p] 
                    #<= (lpSum(omega_allocation[n][p] for n in index_close)
                    #+ (delta_allocation[index][p]*len(index_close)))/(len(index_close)+1), 
                     #"hab_av_" + str(i) + "_" + str(p))           

#### 2.8 Constraint 7 : maximize min accessible forage habitat (Maximin method) 

In [23]:
for p in range(1,n_periods+1):
    cons.update({"period_con_" + str(m) + "_" + str(p):
                 (lpSum(alpha_allocation[m][p] for m in range(n_stands)) >= alpha_min_allocation[p]
        )})

#### 2.9. Constraint 8: Setting some bounds for specific variables (Even-flow) 

In [24]:
#Constraint 11: 
for p in range(2, n_periods+1):
    # bounds on accessible forage habitat (area) 
    ({"alpha_bound"+str(p):lpSum(alpha_allocation[p]*area_dic[N_stands[m]]
                                            for m in range(n_stands))
     <= (1.5)*lpSum(alpha_allocation[p-1]*area_dic[N_stands[m]]
               for m in range(n_stands))})
    ({"alpha_bound_minus"+str(p):lpSum(alpha_allocation[p]*area_dic[N_stands[m]]
                                            for m in range(n_stands)) 
     >= (0.15)*lpSum(alpha_allocation[p-1]*area_dic[N_stands[m]]
               for m in range(n_stands))})
    
   # bounds on timber volume (MBF)
    cons.update({"Y_bound_plus25_"+str(p):(lpSum(Yhp_allocation[m][p][j]*area_dic[N_stands[m]]
           *coeffH_dic[N_stands[m]][str(N_stands[m])+"_"+str(p)+"_"+str(j)]
           for m in range(n_stands) for j in range(n_periods+1)) 
     <= (1.25)*lpSum(Yhp_allocation[m][p-1][j]*area_dic[N_stands[m]]
           *coeffH_dic[N_stands[m]][str(N_stands[m])+"_"+str(p-1)+"_"+str(j)]
                for m in range(n_stands) for j in range(n_periods+1))
          )})
    cons.update({"Y_bound_minus25_"+str(p):(lpSum(Yhp_allocation[m][p][j]*area_dic[N_stands[m]]
           *coeffH_dic[N_stands[m]][str(N_stands[m])+"_"+str(p)+"_"+str(j)]
           for m in range(n_stands) for j in range(n_periods+1)) 
     >= (0.75)*lpSum(Yhp_allocation[m][p-1][j]*area_dic[N_stands[m]]
           *coeffH_dic[N_stands[m]][str(N_stands[m])+"_"+str(p-1)+"_"+str(j)]
                for m in range(n_stands) for j in range(n_periods+1))
          )})
    
    # bounds on harvested land (area)
    ({"Y_bound_plus25_2_"+str(p):lpSum(Y_allocation[m][p]*area_dic[N_stands[m]] for m in range(n_stands)) 
     <= (1.25)*lpSum(Y_allocation[m][p-1]*area_dic[N_stands[m]] for m in range(n_stands))
                })
    ({"Y_bound_min25_2_"+str(p):lpSum(Y_allocation[m][p]*area_dic[N_stands[m]] for m in range(n_stands)) 
     >= (0.75)*lpSum(Y_allocation[m][p-1]*area_dic[N_stands[m]] for m in range(n_stands))
                })
    
    ## bounds on pct treatment (area)
    cons.update({"X_bound_plus25_2_"+str(p):lpSum(X_allocation[m][p]*area_dic[N_stands[m]] for m in range(n_stands)) 
     <= (1.35)*lpSum(X_allocation[m][p-1]*area_dic[N_stands[m]] for m in range(n_stands))
                })
    #+(1-lpSum(X_allocation[m][p-1]for m in range(n_stands))*10)
    cons.update({"X_bound_minus25_2_"+str(p):lpSum(X_allocation[m][p]*area_dic[N_stands[m]] for m in range(n_stands)) 
     >= (0.65)*lpSum(X_allocation[m][p-1]*area_dic[N_stands[m]] for m in range(n_stands))
                })


#### 2.10  Evaluation functions

In [25]:
# count the total number of variables Yhp == 1, must be = n_stands 
cons.update({"sum":lpSum(Yhp_allocation[m][h][p]
                        for m in range(n_stands)
                        for h in range(n_periods+1)
                        for p in range(n_periods+1))==NYhp})

for p in range(n_periods+1):
    # count the number of harvest allocation per period
    cons.update({"TOT_NH_"+str(p):(lpSum(Y_allocation[m][p] for m in range(len(N_stands)))==NH_allocation[p])})
    # count the number of accessible forage habitat per period (number of stands)
    cons.update({"TOT_NAF_"+str(p):(lpSum(alpha_allocation[m][p] for m in range(len(N_stands)))==NAF_allocation[p])})
    # count the number of forage habitat per period (number of stands)
    cons.update({"TOT_D_"+str(p):
                 (lpSum(delta_allocation[m][p] for m in range(len(N_stands)))==ND_allocation[p])})
    # count the number of cover habitat per period (number of stands)
    cons.update({"TOT_NPCT_"+str(p):
                 (lpSum(X_allocation[m][p] for m in range(len(N_stands)))==NPCT_allocation[p])})
    
# count the total volume of timber harvested per period     
for p in range(1,n_periods+1):
    ("TOT_harv_MBF_"+str(p))
    cons.update({"TOT_harv_MBF_"+str(p):(lpSum(Yhp_allocation[m][p][pct]
                 *coeffH_dic[N_stands[m]][str(N_stands[m])+"_"+str(p)+"_"+str(pct)]
                 *area_dic[N_stands[m]]
                 for m in range(n_stands)
                 for pct in range(n_periods+1)
                  )==Vharv_allocation[p])})
    
# count the total area 
cons.update({"Tot_Area":(lpSum(area_dic[i] for i in N_stands)==AREA)})
#var = str(stand)+"_"+str(0)+"_"+str(0)+"_p"+str(p)

# count the area covered by accessible forage habitat 
for j in range(n_periods+1):
    # sum just alpha 
    cons.update({"Area"+str(j):(lpSum(alpha_allocation[i][j]*area_dic[N_stands[i]] 
                for i in range(n_stands))==area_allocation[j])})


### 8. Objective functions 

In [26]:
# Objective function 

r = 3/100 #discounting rate for timber volume (arbitrary)
obj={
    # Accessible forage habitat function 
    0: lpSum(alpha_min_allocation[p] for p in range(1,n_periods+1)),
#obj_func = (lpSum(alpha_allocation[i][j]*area_dic[N_stands[i]] for i in range(n_stands) 
                #for j in range(n_periods+1)))
    # Timber volume function
    1: lpSum(Vharv_allocation[p]*(1/((1+r)**p)) for p in range(1,n_periods+1)),
    #  Carbon stock function
    2: (lpSum(coeffC_dic2[N_stands[m]][str(N_stands[m])+"_"+str(h)+"_"+str(p)]
                *Yhp_allocation[m][h][p]
                *area_dic[N_stands[m]]
                        for m in range(n_stands)
                        for p in range(n_periods+1)
                        for h in range(n_periods+1))),
}

# Variables to obtain objective functions values 
x = {
    0:[alpha_min_allocation[p] for p in range(1,n_periods+1)],
    1:[Vharv_allocation[p]*(1/((1+r)**p)) for p in range(1,n_periods+1)],
    2:[Yhp_allocation[m][p][k]*coeffC_dic2[N_stands[m]][str(N_stands[m])+"_"+str(p)+"_"+str(k)]
                                                        *area_dic[N_stands[m]]
                        for m in range(n_stands)
                        for p in range(n_periods+1)
                        for k in range(n_periods+1)
      ],
}

# calculate objective function values with variables X 
def obj_val(k,a):
    if k == 0:
        return sum(a[0])
    if k == 1:
        return sum(a[1])
    if k == 2:
        return sum(a[2])            

In [ ]:
#Save code into a lp file 
#model.writeLP("model_0628_BFa-min_no-bound.lp")


### 9. Solve the model 

In [ ]:
# Example (timber volume), create one-objective multi-integer programming 
model=LpProblem('Max', LpMaximize)
model+= obj[1]
for i in cons: 
    model+= cons[i]
print(1)
print("model"+str(k))
result = model.solve(CPLEX_CMD(warmStart=True, options=
                                  ["set tune display 2"
                                   , "set mip tolerances integrality 0.01"
                                   , "set mip tolerances mipgap 0.01"
                                    ,"set timelimit 100"
                                   ]))

In [ ]:
# Save the values of variables in a text file 
file_object = open("tim_pct_volbound.txt", 'w') #erase content first
file_object = open("tim_pct_volbound.txt", 'a')
file_object.truncate()
for v in model.variables():
    var=int(v.varValue)
    if var >=1:
        file_object.write(str(v.name)+ "="+ str(v.varValue))
        file_object.write('\n')
file_object.close()

In [ ]:
# Example (accessible forage habitat objective function), create one-objective multi-integer programming 
model=LpProblem('Max', LpMaximize)
model+= obj[0]
for i in cons: 
    model+= cons[i]
print(1)
print("model"+str(k))
result = model.solve(CPLEX_CMD(keepFiles=True, warmStart=True, options=
                                  ["set tune display 2"
                                   , "set mip tolerances integrality 0.01"
                                   , "set mip tolerances mipgap 0.01"
                                    ,"set timelimit 700"
                                   ]))
file_object = open("alpha_pct.txt", 'w')
file_object = open("alpha_pct.txt", 'a')
file_object.truncate()
for v in model.variables():
    var=int(v.varValue)
    if var >=1:
        file_object.write(str(v.name)+ "="+ str(v.varValue))
        file_object.write('\n')
file_object.close()

In [ ]:
# Example (carbon stock), create one-objective multi-integer programming 
model=LpProblem('Max', LpMaximize)
model+= obj[2]
for i in cons: 
    model+= cons[i]
print(1)
print("model"+str(k))
result = model.solve(CPLEX_CMD(keepFiles=True, warmStart=True, options=
                                  ["set tune display 2"
                                   , "set mip tolerances integrality 0.01"
                                   , "set mip tolerances mipgap 0.01"
                                    ,"set timelimit 100"
                                   ]))
file_object = open("carbon_pct.txt", 'w')
file_object = open("carbon_pct.txt", 'a')
file_object.truncate()
for v in model.variables():
    var=int(v.varValue)
    if var >=1:
        file_object.write(str(v.name)+ "="+ str(v.varValue))
        file_object.write('\n')
file_object.close()

In [ ]:
#play around with CBC solver 
#model.solve(PULP_CBC_CMD(msg=1))
#status =  LpStatus[model.status]
#print(status)

    #https://github.com/IBMDecisionOptimization/docplex-examples/tree/master/examples
    ### https://github.com/IBMDecisionOptimization/docplex-examples/blob/master/examples/mp/jupyter/progress.ipynb

### 10. Solve multi-objective mathematical programming model 

In [27]:
# Call CPLEX 
#"C:\Program Files\IBM\ILOG\CPLEX_Studio221\cplex\bin\x64_win64\cplex.exe"
path_to_cplex = r'C:\Program Files\IBM\ILOG\CPLEX_Studio221\cplex\bin\x64_win64\cplex.exe'
solver = CPLEX_CMD(path=path_to_cplex)
#status = CPXsetdblparam(path_to_cplex, CPX_PARAM_TILIM, 300)
#solver = CPLEX_PY()
#status = model.solve(solver)

    

##### Generate the payoff table - lexicographic optimization

In [ ]:
model_count=0
# Generate the payoff table 
## lexicographic optimization 
payoff=np.zeros([len(obj),len(obj)])
for k in range(0,len(obj)):
    model=LpProblem('Max', LpMaximize)
    model+= obj[k]
    for i in cons: 
        model+= cons[i]
    print(1)
    print("model"+str(k))
    result = model.solve(CPLEX_CMD(keepFiles=True, warmStart=True, options=
                                   ["set tune display 2"
                                   , "set mip tolerances integrality 0.01"
                                   , "set mip tolerances mipgap 0.01" #optimality gap would be 1%
                                    ,"set timelimit 900"
                                   ]))
    file_object = open(str(model_count)+"Biomass0.txt", 'w')
    file_object = open(str(model_count)+"Biomass0.txt", 'a')
    for v in model.variables():
        file_object.write(str(v.name)+ "="+ str(v.varValue))
        file_object.write('\n')
    file_object.close()
    model_count=model_count+1
    #prob.solve(CPLEX_CMD(options=['set mip tolerances mipgap 0.25']))
    print(str(LpStatus[result]))
    if LpStatus[result]=="Optimal":
        print(str(LpStatus[result])+" ; max value = "+str(value(model.objective)))
        payoff[k,k]= value(model.objective);
        kp=k+1;
        model = LpProblem("Max",LpMaximize)
        while kp<= len(obj)-1:
                model += obj[kp]
                print("model"+str(kp))
                if kp-1>=0:
                    model += obj[kp-1] >= payoff[k,kp-1]
                    print("model_payoff"+str(kp-1))
                    print("payoff"+ str(payoff[k,kp-1]))
                for i in cons:
                    model += cons[i]
                print(2)
                result = model.solve(CPLEX_CMD(keepFiles=True, warmStart=True, options=
                                   ["set tune display 2"
                                   , "set mip tolerances integrality 0.01"
                                   , "set mip tolerances mipgap 0.01"
                                    ,"set timelimit 900"
                                   ]))
                file_object = open(str(model_count)+"payoffsol.txt", 'w')
                file_object = open(str(model_count)+"payoffsol.txt", 'a')
                for v in model.variables():
                    file_object.write(str(v.name)+ "="+ str(v.varValue))
                    file_object.write('\n')
                file_object.close()
                model_count=model_count+1
                if LpStatus[result] == 'Optimal':
                    print(str(LpStatus[result])+" ; max value = "+str(value(model.objective)))
                    payoff[k,kp]= value(model.objective)
                    print(payoff[k,kp], "payoff")
                    kp += 1     
                else:
                    sys.exit('no optimal solution for mod_payoff')
        kp=0;
        model += obj[k] >= payoff[k,k]
        print("model_payoff"+str(k))
        print("payoff"+ str(payoff[k,k]))
        while kp< k:
            model += obj[kp]
            print("model_"+str(kp))
            if kp-1>=0:
                model += obj[kp-1] >= payoff[k,kp-1]
                print("model_payoff"+str(kp-1))
                print("payoff"+ str(payoff[k,kp-1]))
            for i in cons:
                model += cons[i]
            print(3)
            result = model.solve(CPLEX_CMD(keepFiles=True, warmStart=True, options=
                                   ["set tune display 2"
                                   , "set mip tolerances integrality 0.01"
                                   , "set mip tolerances mipgap 0.01"
                                    ,"set timelimit 900"
                                   ]))
            file_object = open(str(model_count)+"payoffsol.txt", 'w')
            file_object = open(str(model_count)+"payoffsol.txt", 'a')
            for v in model.variables():
                file_object.write(str(v.name)+ "="+ str(v.varValue))
                file_object.write('\n')
            file_object.close()
            model_count=model_count+1
            if LpStatus[result] == 'Optimal':
                print(str(LpStatus[result])+" ; max value = "+str(value(model.objective)))
                payoff[k,kp]= value(model.objective)
                kp += 1
            else:
                sys.exit('no optimal solution for mod_payoff')   
    else:
        sys.exit('no optimal solution for mod_payoff')

In [ ]:


list0=[]
list0.append(payoff[0][0])
list0.append(payoff[1][0])
list0.append(payoff[2][0])

list1=[]
list1.append(payoff[0][1])
list1.append(payoff[1][1])
list1.append(payoff[2][1])

list2=[]
list2.append(payoff[0][2])
list2.append(payoff[1][2])
list2.append(payoff[2][2])
df = pd.DataFrame({
    "f1": list0,
    "f2": list1,
    "f3": list2,
})
df.to_csv("payoff_ordi_biomass0.xlsx")

In [28]:
payoff=np.zeros([len(obj),len(obj)])
payoff[0][0] = 3.21000000e+02
payoff[1][0] = 1.67000000e+02
payoff[2][0] = 2.20000000e+01
payoff[0][1] = 1.32537645e+05
payoff[1][1] = 1.42748151e+05
payoff[2][1] = 0 
payoff[0][2] = 1.04802000e+05
payoff[1][2] = 1.21577000e+05
payoff[2][2] = 5.48722000e+05

print(payoff)

"""[[4.31000000e+02 1.33314475e+05 1.94145000e+05]
 [1.26000000e+02 1.47458856e+05 8.34840000e+05]
 [5.20000000e+01 1.46209593e+05 1.40709000e+06]]
[[4.27000000e+02 1.65402075e+06 1.41496500e+06]
 [4.28000000e+02 1.65402075e+06 1.41496500e+06]
 [4.28000000e+02 1.32643e+06 1.41496500e+06]]
[[4.31000000e+02 1.65402075e+06 1.41496500e+06]
 [4.28000000e+02 1.65402075e+06 1.41496500e+06]
 [4.28000000e+02 1.65402075e+06 1.41496500e+06]]"""

[[3.21000000e+02 1.32537645e+05 1.04802000e+05]
 [1.67000000e+02 1.42748151e+05 1.21577000e+05]
 [2.20000000e+01 0.00000000e+00 5.48722000e+05]]


'[[4.31000000e+02 1.33314475e+05 1.94145000e+05]\n [1.26000000e+02 1.47458856e+05 8.34840000e+05]\n [5.20000000e+01 1.46209593e+05 1.40709000e+06]]\n[[4.27000000e+02 1.65402075e+06 1.41496500e+06]\n [4.28000000e+02 1.65402075e+06 1.41496500e+06]\n [4.28000000e+02 1.32643e+06 1.41496500e+06]]\n[[4.31000000e+02 1.65402075e+06 1.41496500e+06]\n [4.28000000e+02 1.65402075e+06 1.41496500e+06]\n [4.28000000e+02 1.65402075e+06 1.41496500e+06]]'

##### Pareto front Augmecon_R

In [ ]:
### Pareto front AUGMECON-R
### adapted from https://www.researchgate.net/publication/341610213_A_robust_augmented_e-constraint_method_AUGMECON-R_for_finding_exact_solutions_of_multi-objective_linear_programming_problems
### https://github.com/KatforEpu/Augmecon-R ### GAMS
### https://link.springer.com/article/10.1007/s12351-020-00574-6
minobj=np.zeros([len(obj),1]);
maxobj=np.zeros([len(obj),1]);
for k in range(0,len(obj)):
        minobj[k] = min(payoff[:,k]);
        maxobj[k] = max(payoff[:,k]);

s = {
     1: LpVariable("s2",lowBound = 0),
     2: LpVariable("s3",lowBound = 0),
     }

lst = []
gridpoints=[[]]
count2 = 0
count1 = 0 
model_count = 0 
count=0
g1= 100
g2= 100 #shall we update? 
flag = {}

for i in range(0,g1+1): # instead of g2+1 ? 
    for j in range(0,g2+1):
        var = str(j)+"_"+str(i)
        flag.update({var:0})
n=0 
b1 = 0
b2 = 0 
step1=(maxobj[1]-minobj[1])/g1
step2=(maxobj[2]-minobj[2])/g2
count2 = count2 + 1
count1 = count1 + 1 
while count2 < g2:
    print("count2_:"+ str(count2))
    print("count1_:"+ str(count1))
    var = str(count1)+"_"+str(count2)
    if flag[var] == 0:
        print(str(n)+"flag")
        model = LpProblem("Max",LpMaximize)
        code1 = 1/(maxobj[1]-minobj[1]);
        code2 = 1/(maxobj[2]-minobj[2])
        model += obj[0]+1e-3*(s[1]*code1+s[2]*1e-1*code2) #epsilon between 1e-3 and 1e-6 
        #model += obj[1]- s[1] == maxobj[1] - ((count1)/g1)*(maxobj[1]- minobj[1])
        #model += obj[2]- s[2] == maxobj[2] - ((count2)/g2)*(maxobj[2]- minobj[2])
        model += obj[1]- s[1] == minobj[1] + ((count1)*step1)
        model += obj[2]- s[2] == minobj[2] + ((count2)*step2)
        print("yeah_still_here")
        for i in cons:
            model += cons[i]
        result = model.solve(CPLEX_CMD(keepFiles=True, warmStart=True, options=
                                   ["set tune display 2"
                                   #, "set mip tolerances objdifference 10"
                                   , "set mip tolerances mipgap 0.01"
                                    , "set timelimit 720"
                                   ]))
        file_object = open(str(model_count)+"solpareto.txt", 'w')
        file_object = open(str(model_count)+"solpareto", 'a')
        file_object.truncate()
        for v in model.variables():
            file_object.write(str(v.name)+ "="+ str(v.varValue))
            file_object.write('\n')
        file_object.close()
        model_count=model_count+1
        print(LpStatus[result]+str(n)) 
        if LpStatus[result] == 'Optimal':
            print("try"+ str(n))
            ### need to adapt function to get the value of a 3D graph 
            d = ({
            0:[value(x[0][p]) for p in range(1,n_periods)],
            1:[value(x[1][p]) for p in range(1,n_periods)],
            2:[value(x[2][p]) for p in range(len(x[2])) ]}) #not sure for the carbon 
            for k in range(0,len(obj)):
                lst= np.append(lst,obj_val(k, d))
            gridpoints = np.append(gridpoints,lst)
            ##############################
            n = n + 1
            s1=value(s[1])
            print(s1,"s1")
            s2=value(s[2])
            print(s2, "s2")
            b1 = int(s1/step1)
            b2 = int(s2/step2)
            print(b2, "b2")
            for i in range(count2, count2+b2):
                var=str(count1)+"_"+str(i)
                flag.update({var:b1+1})
            if count1 < g1:
                count1=count1+1
                print(count1,"count1_add")
                continue 
            else: 
                count1=0
                if count2 < g2:
                    count2=count2+1
                    count1=count1+1
                    continue
                else:
                    print('early exit (jump) 1')
                    break
        else: 
            print("infeasible")
            for i in range(count2, g2):
                var=str(count1)+"_"+str(i)
                flag.update({var:g1-count1+1})
            count1 = 0 
            if count2 < g2:
                count2=count2+1
                count1=count1+1
                continue
            else:
                print('early exit (jump) 2')
                break
    else: 
        print(str(n)+"flag_not_0")
        count1 = count1+flag[var]
        print(count1, "count1+flag")
        if count1 <= g1:
            var=str(count1)+"_"+str(count2)
            print(var, 'new_flag')
            continue
        else: 
            count1 = 0
            if count2 < g2: 
                count2=count2+1
                print(count2, "flag_not_0_count1_restart")
                count1=count1+1
                print(count1, "count1")
                continue
            else: 
                print('early exit (jump) 3')
                break 
                

count2_:1
count1_:1
0flag
yeah_still_here
Optimal0
try0
124342.57446071175 s1
876.8000000000029 s2
0 b2
2 count1_add
count2_:1
count1_:2
1flag
yeah_still_here
Optimal1
try1
124342.57446071175 s1
876.8000000000029 s2
0 b2
3 count1_add
count2_:1
count1_:3
2flag
yeah_still_here
Optimal2
try2
120297.59851888282 s1
419.8000000000029 s2
0 b2
4 count1_add
count2_:1
count1_:4
3flag
yeah_still_here
Optimal3
try3
120457.12804908639 s1
1454.800000000003 s2
0 b2
5 count1_add
count2_:1
count1_:5
4flag
yeah_still_here
Optimal4
try4
119029.64653908639 s1
1454.800000000003 s2
0 b2
6 count1_add
count2_:1
count1_:6
5flag
yeah_still_here
Optimal5
try5
117602.16502908639 s1
1454.800000000003 s2
0 b2
7 count1_add
count2_:1
count1_:7
6flag
yeah_still_here
Optimal6
try6
116174.6835190864 s1
1454.800000000003 s2
0 b2
8 count1_add
count2_:1
count1_:8
7flag
yeah_still_here
Optimal7
try7
114747.2020090864 s1
1454.800000000003 s2
0 b2
9 count1_add
count2_:1
count1_:9
8flag
yeah_still_here
Optimal8
try8
113319.720

##### Firt maps to check results 

In [ ]:

import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator
import numpy as np

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})


# Make data.
print(len(gridpoints)/3)
X=list()
Y=list()
Z=list()
count=0
for i in range(0,int(len(gridpoints)/3)):
    if count <=len(gridpoints)-1:
        X.append(gridpoints[count])
        Y.append(gridpoints[count+1])
        Z.append(gridpoints[count+2])
        count=(i+1)*3
        
df = pd.DataFrame({
    "f1": X,
    "f2": Y,
    "f3": Z,
})

#X = np.arange(-5, 5, 0.25)
#Y = np.arange(-5, 5, 0.25)
X=np.array(X)
Y=np.array(Y)
Z=np.array(Z)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(X,Y,Z)
plt.show()

df.to_csv("output_p55.xlsx")
#df.to_csv("output_lesssimp_noOG.xlsx")
#df.to_csv("output_OG.xlsx")
print(df)

In [ ]:
#FUN 
model=LpProblem('Max', LpMaximize)
code1 = 1/(maxobj[1]-minobj[1]);
code2 = 1/(maxobj[2]-minobj[2])
model+= obj[0] +1e-3*(s[1]*code1+s
    model+= cons[i]      
model.writeLP("model_optimal_sol.lp")
print(obj[1])


### COMMENTS

In [ ]:
# Search for nadir points, make sure that AUGMECON is well implemented 
# Use another algorithm 
# Try Pyomo (python package), try GAMS 